apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: trend-mirror
  # annotations:  <-- 삭제
  #   kubernetes.io/ingress.class: nginx  <-- 삭제
spec:
  # ingressClassName: nginx  <-- 삭제
  rules:
  - host: upstage-woojun.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8002
      - path: /trendmirror
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
